# Generated by Django 6.0 on 2025-12-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of the page to parse')),
                ('window_selector', models.CharField(help_text='CSS selector for the window to wait for', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the task is currently running')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
