# Generated by Django 6.0 on 2025-12-30 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsingtask',
            name='window_selector',
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='events_container_selector',
            field=models.CharField(default='body > kp-app > div > kp-authorized > section > main > ng-component > div > div > kp-alarm-monitor-event-feed > div > section > div > div > syn-card-list > div', help_text='CSS selector for events container', max_length=255),
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='login_url',
            field=models.URLField(help_text='URL for login', null=True),
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='monitoring_url',
            field=models.URLField(help_text='URL of the monitoring page', null=True),
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='new_events_button_selector',
            field=models.CharField(default='.kp-load-new-events', help_text="CSS selector for 'New events' button", max_length=255),
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='password',
            field=models.CharField(help_text='Password for login', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='read_all_button_selector',
            field=models.CharField(default="button:contains('Прочитать все')", help_text="CSS selector for 'Read all' button", max_length=255),
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='token',
            field=models.CharField(blank=True, help_text='Bearer token', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='username',
            field=models.CharField(help_text='Username for login', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_data', models.JSONField(help_text='Parsed event data')),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('parsing_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agromash.parsingtask')),
            ],
        ),
    ]
