# Generated by Django 6.0 on 2025-12-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0002_remove_parsingtask_window_selector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingtask',
            name='token',
            field=models.TextField(blank=True, help_text='Bearer token', null=True),
        ),
    ]
