# Generated by Django 6.0 on 2025-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0003_alter_parsingtask_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingtask',
            name='alarm_monitor_name',
            field=models.CharField(help_text='Name of the alarm monitor to select', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parsingtask',
            name='monitors_list_selector',
            field=models.CharField(default='body > kp-app > div > kp-authorized > section > main > ng-component > div > kp-alarm-monitors-dashboard-list > div > div.kp-monitor-list-wrapper > div.kp-monitors-dashboard__list', help_text='CSS selector for monitors list', max_length=255),
        ),
    ]
