# Generated by Django 6.0 on 2025-12-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0004_parsingtask_alarm_monitor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVideoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Account name', max_length=255)),
                ('password', models.CharField(help_text='Account password', max_length=255)),
                ('contract', models.CharField(help_text='Contract number', max_length=255)),
                ('organization', models.CharField(help_text='Organization name', max_length=255)),
            ],
        ),
    ]
