# Generated by Django 6.0 on 2025-12-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0005_accountvideoanalytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ParsingTask',
        ),
    ]
