# Generated by Django 6.0 on 2025-12-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0006_delete_event_delete_parsingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvideoanalytics',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountvideoanalytics',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
