# Generated by Django 6.0 on 2025-12-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0007_accountvideoanalytics_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_id', models.IntegerField()),
                ('monitor_name', models.CharField(max_length=255)),
                ('alarm_id', models.CharField(max_length=255, unique=True)),
                ('topic', models.CharField(max_length=255)),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('event_id', models.BigIntegerField()),
                ('original_quality_snapshot', models.TextField(blank=True, null=True)),
                ('plate_identities', models.JSONField(blank=True, null=True)),
                ('face_identities', models.JSONField(blank=True, null=True)),
                ('snapshots', models.JSONField(blank=True, null=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
