# Generated by Django 6.0 on 2025-12-31 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0008_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agromash.accountvideoanalytics'),
            preserve_default=False,
        ),
    ]
