# Generated by Django 6.0 on 2025-12-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0009_alarm_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('subscribed_monitors', models.JSONField(default=list)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
