# Generated by Django 6.0 on 2025-12-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0010_telegramsubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_id', models.CharField(max_length=255, unique=True)),
                ('monitor_name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
