# Generated by Django 6.0 on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agromash", "0011_monitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountvideoanalytics",
            name="parser_status",
            field=models.CharField(
                choices=[
                    ("stopped", "Stopped"),
                    ("starting", "Starting"),
                    ("running", "Running"),
                    ("stopping", "Stopping"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="stopped",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="accountvideoanalytics",
            name="parser_task_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accountvideoanalytics",
            name="parser_stop_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accountvideoanalytics",
            name="parser_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountvideoanalytics",
            name="parser_stopped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountvideoanalytics",
            name="parser_heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountvideoanalytics",
            name="parser_last_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]

