# Generated by Django 6.0 on 2026-01-01

from django.db import migrations, models
import django.db.models.deletion


def forwards_migrate_subscriptions(apps, schema_editor):
    TelegramSubscriber = apps.get_model('agromash', 'TelegramSubscriber')
    Monitor = apps.get_model('agromash', 'Monitor')
    Subscription = apps.get_model('agromash', 'TelegramSubscriberMonitorSubscription')

    for subscriber in TelegramSubscriber.objects.all().only('id', 'subscribed_monitor_ids'):
        ids = subscriber.subscribed_monitor_ids or []
        for mid in ids:
            try:
                monitor = Monitor.objects.filter(monitor_id=str(mid)).first()
                if not monitor:
                    continue
                Subscription.objects.get_or_create(subscriber_id=subscriber.id, monitor_id=monitor.id)
            except Exception:
                # best-effort: не заваливаем миграцию из-за единичных неконсистентных данных
                continue


def backwards_migrate_subscriptions(apps, schema_editor):
    # Обратная миграция не восстанавливает legacy JSON.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0012_accountvideoanalytics_parser_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramsubscriber',
            old_name='subscribed_monitors',
            new_name='subscribed_monitor_ids',
        ),
        migrations.CreateModel(
            name='TelegramSubscriberMonitorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agromash.monitor')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agromash.telegramsubscriber')),
            ],
            options={
                'db_table': 'subscribed_monitors',
                'verbose_name': 'Подписка на монитор',
                'verbose_name_plural': 'Подписки на мониторы',
                'unique_together': {('subscriber', 'monitor')},
            },
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='subscribed_monitors',
            field=models.ManyToManyField(
                blank=True,
                related_name='subscribers',
                through='agromash.TelegramSubscriberMonitorSubscription',
                to='agromash.monitor',
                verbose_name='Подписанные мониторы',
            ),
        ),
        migrations.RunPython(forwards_migrate_subscriptions, backwards_migrate_subscriptions),
    ]
