# Generated by Django 6.0 on 2026-01-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agromash", "0013_subscribed_monitors_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramReportSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_from_minutes", models.PositiveIntegerField(default=60, verbose_name="Период ОТ (минут назад)")),
                (
                    "period_to_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 означает 'по текущее время'.",
                        verbose_name="Период ДО (минут назад)",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("10m", "Каждые 10 минут"),
                            ("hourly", "Каждый час"),
                            ("daily", "Каждый день"),
                            ("weekly", "Каждую неделю"),
                            ("monthly", "Каждый месяц"),
                        ],
                        default="hourly",
                        max_length=16,
                        verbose_name="Частота отправки",
                    ),
                ),
                ("send_pdf", models.BooleanField(default=True, verbose_name="Отправлять PDF")),
                ("send_xlsx", models.BooleanField(default=True, verbose_name="Отправлять Excel (XLSX)")),
                ("enabled", models.BooleanField(default=True, verbose_name="Включено")),
                (
                    "last_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последняя отправка"),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Следующая отправка"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_subscriptions",
                        to="agromash.telegramsubscriber",
                        verbose_name="Подписчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на отчёты",
                "verbose_name_plural": "Подписки на отчёты",
            },
        ),
        migrations.AddField(
            model_name="telegramreportsubscription",
            name="monitors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Если не выбрать мониторы — отчёт будет по всем мониторам.",
                related_name="report_subscriptions",
                to="agromash.monitor",
                verbose_name="Мониторы",
            ),
        ),
    ]

