# Generated by Django 6.0 on 2026-01-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agromash", "0014_telegramreportsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("chat_id", models.BigIntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("photo", "Photo"),
                            ("document", "Document"),
                        ],
                        db_index=True,
                        default="message",
                        max_length=16,
                    ),
                ),
                ("ok", models.BooleanField(db_index=True, default=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("text", models.TextField(blank=True)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "alarm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_event_logs",
                        to="agromash.alarm",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_event_logs",
                        to="agromash.telegramsubscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram log",
                "verbose_name_plural": "Telegram logs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReportRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("ok", models.BooleanField(db_index=True, default=True)),
                ("error", models.TextField(blank=True)),
                ("alarms_count", models.PositiveIntegerField(default=0)),
                ("attachments_count", models.PositiveIntegerField(default=0)),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_run_logs",
                        to="agromash.telegramsubscriber",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_logs",
                        to="agromash.telegramreportsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report run log",
                "verbose_name_plural": "Report run logs",
                "ordering": ("-created_at",),
            },
        ),
    ]

