# Generated by Django 6.0 on 2026-01-10 10:44

import agromash.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0024_subscribed_monitors_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Карточка события',
                'verbose_name_plural': 'Карточки событий',
            },
        ),
        migrations.CreateModel(
            name='AlarmDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=agromash.models._alarm_document_upload_to)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Документ события',
                'verbose_name_plural': 'Документы событий',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='UserMonitorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='Если выключено — монитор не доступен пользователю в web-интерфейсе.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Доступ пользователя к монитору',
                'verbose_name_plural': 'Доступ пользователей к мониторам',
            },
        ),
        migrations.AddField(
            model_name='alarm',
            name='monitor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='agromash.monitor'),
        ),
        migrations.AddField(
            model_name='alarmcase',
            name='alarm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='agromash.alarm'),
        ),
        migrations.AddField(
            model_name='alarmcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_cases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarmcase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_cases_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarmdocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agromash.alarmcase'),
        ),
        migrations.AddField(
            model_name='alarmdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermonitoraccess',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='agromash.monitor'),
        ),
        migrations.AddField(
            model_name='usermonitoraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usermonitoraccess',
            unique_together={('user', 'monitor')},
        ),
    ]
