# Generated by Kilo Code on 2026-01-10

from django.db import migrations


def _forward(apps, schema_editor):
    Alarm = apps.get_model('agromash', 'Alarm')
    Monitor = apps.get_model('agromash', 'Monitor')

    # Map numeric monitor_id -> Monitor.pk
    mapping = {}
    for m in Monitor.objects.all().values('id', 'monitor_id'):
        try:
            mapping[int(m.get('monitor_id') or 0)] = int(m['id'])
        except Exception:
            continue

    if not mapping:
        return

    batch = []
    qs = Alarm.objects.filter(monitor_ref__isnull=True).only('id', 'monitor_id')
    for a in qs.iterator(chunk_size=2000):
        mid = mapping.get(int(getattr(a, 'monitor_id', 0) or 0))
        if not mid:
            continue
        a.monitor_ref_id = mid
        batch.append(a)
        if len(batch) >= 1000:
            Alarm.objects.bulk_update(batch, ['monitor_ref'])
            batch = []

    if batch:
        Alarm.objects.bulk_update(batch, ['monitor_ref'])


def _backward(apps, schema_editor):
    Alarm = apps.get_model('agromash', 'Alarm')
    Alarm.objects.update(monitor_ref=None)


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0025_alarmcase_alarmdocument_usermonitoraccess_and_more'),
    ]

    operations = [
        migrations.RunPython(_forward, _backward),
    ]

