# Generated by Django 6.0 on 2026-01-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0026_alarm_monitor_ref_backfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramreportsubscription',
            options={'verbose_name': 'Report subscription', 'verbose_name_plural': 'Report subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='usermonitoraccess',
            options={'permissions': (('can_view_events', 'Can view events dashboard'),), 'verbose_name': 'Доступ пользователя к монитору', 'verbose_name_plural': 'Доступ пользователей к мониторам'},
        ),
        migrations.RenameIndex(
            model_name='fueloperation',
            new_name='agromash_fu_card_nu_2b0ecf_idx',
            old_name='agromash_fue_card_n_1dfc15_idx',
        ),
        migrations.AlterField(
            model_name='fueloperation',
            name='fallback_plate_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Если PlateIdentity не подобран по card_number -> owner_middle_name — список уникальных объектов plates (из Alarm.plate_identities) для matched_alarms.'),
        ),
        migrations.AlterField(
            model_name='telegramsubscriber',
            name='subscribed_monitor_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
