# Generated by Django 6.0 on 2026-02-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0027_alter_telegramreportsubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreport',
            name='analysis_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='analysis_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='analysis_status',
            field=models.CharField(choices=[('none', 'Not started'), ('pending', 'Running'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='analysis_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
