# Generated by Django 6.0 on 2026-08-27 09:40

import agromash.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0029_alarm_indexes_concurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvideoanalytics',
            name='password',
            field=agromash.fields.EncryptedCharField(help_text='Account password (зашифрован в БД)', max_length=500),
        ),
    ]
