# Generated by Django 6.0 on 2026-08-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0031_encrypt_existing_va_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvideoanalytics',
            name='parser_restart_attempt',
            field=models.PositiveIntegerField(default=0, help_text='Счётчик последовательных падений подряд (эпизод флаппинга). Сбрасывается, если между падениями прошло больше PARSER_BACKOFF_EPISODE_WINDOW_MIN минут — см. auto_restart_error_parsers.'),
        ),
    ]
