# Generated by Django 6.0 on 2026-08-28 06:54

import agromash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0032_accountvideoanalytics_parser_restart_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to=agromash.models._alarm_video_clip_upload_to),
        ),
        migrations.AddField(
            model_name='alarm',
            name='video_clip_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='video_clip_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='video_clip_status',
            field=models.CharField(blank=True, choices=[('pending', 'Скачивается'), ('ready', 'Готово'), ('error', 'Ошибка')], help_text='Пусто — запись видео не включена для монитора этого события.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='record_video_enabled',
            field=models.BooleanField(default=False, help_text='Скачивать видео-клип VMS-архива для новых Alarm с этого монитора.', verbose_name='Записывать видео'),
        ),
    ]
