# Generated by Django 6.0 on 2026-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromash', '0033_alarm_video_clip_alarm_video_clip_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvideoanalytics',
            name='parser_restart_attempt',
            field=models.PositiveIntegerField(default=0, help_text='Счётчик последовательных падений подряд (эпизод флаппинга). Сбрасывается в 0, когда парсер отработал без сбоев PARSER_SUSTAINED_SUCCESS_MIN минут подряд — см. check_parser_heartbeats.'),
        ),
    ]
