"""
Django settings for btkanalitics project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# Отдельный от SECRET_KEY ключ для шифрования полей в БД (например,
# AccountVideoAnalytics.password) — см. agromash/fields.py. Ротация
# SECRET_KEY (разлогинивает пользователей) не должна одновременно
# делать нечитаемыми уже зашифрованные данные в БД.
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',')
BASE_URL = config('BASE_URL')

# Хост, для которого форсируем HTTPS-редирект и Secure-флаг на куках
# (см. btkanalitics.middleware.ConditionalHttpsMiddleware). Прямой LAN-доступ
# (localhost, 10.0.0.2:9091 и т.п. из ALLOWED_HOSTS) продолжает работать
# по обычному HTTP — эти хосты не попадают под харднинг.
PUBLIC_HTTPS_HOST = config('PUBLIC_HTTPS_HOST', default='btkanylitics.babtsou.uk')
TLG_BOT_TOKEN = config('TLG_BOT_TOKEN')
TLG_CHAT_ID = config('TLG_CHAT_ID')
TLG_CHAT_ID_ADMINS = [ x for x in config("TLG_CHAT_ID_ADMINS", default="").split(",") if x ]

# -----------------
# Email (SMTP)
# -----------------
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=20, cast=int)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'webmaster@localhost')
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agromash.apps.AgromashConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'btkanalitics.middleware.ConditionalHttpsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# В браузерах COOP (Cross-Origin-Opener-Policy) игнорируется на непроверенных origin (например, http://10.x.x.x),
# из-за чего в консоли появляется предупреждение. Для внутреннего HTTP-доступа отключаем заголовок.
# Если проект будет обслуживаться по HTTPS — можно вернуть 'same-origin'.
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Публичный домен обслуживается через Cloudflare (TLS терминируется на её
# стороне) и доходит до Django через трёххоповую цепочку:
#   Cloudflare -> nginx:443 (ssl_proxy_root) на 52.207.37.113 (хардкодит
#   X-Forwarded-Proto: https) -> nginx:80 (btkanylitics) на 10.0.0.5
#   -> nginx:9091 на этом сервере -> gunicorn:8091.
#
# ВАЖНО: живой конфиг на КАЖДОМ из этих трёх хостов — это отдельный файл
# в /etc/nginx/sites-enabled/, который НЕ синхронизируется автоматически
# ни с этим репозиторием, ни между хостами. `git pull` на 10.0.0.2 не
# трогает nginx вообще. При любой правке заголовков/прокси — обязательно
# вручную применять на всех трёх хостах и проверять результат через
# staff-only /agromash/_debug/headers/ (см. agromash/views.py), а не только
# косвенно по отсутствию редиректа — так уже прятался баг несколько часов.
# Подтверждено этим способом: is_secure=true для публичного трафика.
#
# SECURE_SSL_REDIRECT сознательно НЕ используется — вместо него
# ConditionalHttpsMiddleware редиректит на HTTPS и форсирует Secure-флаг
# на куках только для PUBLIC_HTTPS_HOST, т.к. http://10.0.0.2:9091 всё ещё
# используется как прямой LAN-доступ в обход прокси-цепочки, и глобальный
# SECURE_SSL_REDIRECT/COOKIE_SECURE сломал бы там логин.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'btkanalitics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Важно: overrides Django admin шаблонов (base_site.html, index.html)
        # лежат в `agromash/templates/`. Добавляем этот путь в DIRS, иначе
        # при APP_DIRS=True будет браться шаблон из `django.contrib.admin`
        # (так как он идет раньше в INSTALLED_APPS).
        'DIRS': [BASE_DIR / 'agromash' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'btkanalitics.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True

# Django 6+: явный тип PK по умолчанию (убирает предупреждения W042)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media uploads (AlarmDocument.file, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/events/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# -----------------
# Celery
# -----------------
# Ожидается, что в окружении задан брокер (например Redis).
# Значения по умолчанию оставлены максимально простыми для локальной разработки.
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=CELERY_BROKER_URL)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = config('CELERY_TASK_TIME_LIMIT', default=60 * 60 * 24, cast=int)
CELERY_TASK_SOFT_TIME_LIMIT = config('CELERY_TASK_SOFT_TIME_LIMIT', default=60 * 60 * 23, cast=int)
CELERY_WORKER_PREFETCH_MULTIPLIER = config('CELERY_WORKER_PREFETCH_MULTIPLIER', default=1, cast=int)
CELERY_TASK_ACKS_LATE = True

# Для «вечных» задач Celery (long-running loops) глобальный time limit не подходит.
#
# Важно: в некоторых версиях Celery/конфигурациях значение `None` для time_limit
# в аннотациях/декораторе может интерпретироваться как «использовать дефолтный лимит».
# Чтобы гарантированно не получать TimeLimitExceeded/SoftTimeLimitExceeded,
# ставим очень большой лимит (по сути «безлимит»).
#
# Остальные задачи продолжают использовать глобальные лимиты выше.
VA_PARSER_TIME_LIMIT_SEC = 60 * 60 * 24 * 365 * 10  # 10 лет
VA_PARSER_SOFT_TIME_LIMIT_SEC = VA_PARSER_TIME_LIMIT_SEC - 60  # даём 60с на graceful shutdown

# Для SSE-парсера переопределяем лимиты времени.
#
CELERY_TASK_ANNOTATIONS = {
    "agromash.parse_event": {
        "time_limit": VA_PARSER_TIME_LIMIT_SEC,
        "soft_time_limit": VA_PARSER_SOFT_TIME_LIMIT_SEC,
    },
    # На всякий случай добавляем алиас по полному пути функции.
    # (В норме используется name из декоратора, но это защищает от рассинхрона.)
    "agromash.tasks.parse_event_task": {
        "time_limit": VA_PARSER_TIME_LIMIT_SEC,
        "soft_time_limit": VA_PARSER_SOFT_TIME_LIMIT_SEC,
    },
}

# «Вечные» SSE-парсер-задачи изолированы в отдельную очередь `parser`,
# которую слушает отдельный воркер на пуле потоков (--pool=threads), а не
# стандартный prefork-воркер (см. deploy/systemd/btkanalitics-celery-worker-parser.service).
# Раньше эти задачи навсегда занимали слоты обычного prefork-воркера
# (concurrency = nproc), из-за чего короткие задачи (отчёты, анализ,
# heartbeat) конкурировали с ними за те же слоты — это и было основной
# причиной роста RSS и аккаунтов, зависающих в статусе "starting".
CELERY_TASK_ROUTES = {
    "agromash.parse_event": {"queue": "parser"},
}

# -----------------
# VA SSE Parser settings
# -----------------
# Таймаут на установку соединения с SSE endpoint (секунды).
# Если сервер VA медленно отвечает — увеличьте это значение.
VA_SSE_CONNECT_TIMEOUT_SEC = config('VA_SSE_CONNECT_TIMEOUT_SEC', default=15.0, cast=float)

# Таймаут на чтение данных из SSE (секунды).
# Должен быть большим, т.к. SSE — долгоживущее соединение.
VA_SSE_READ_TIMEOUT_SEC = config('VA_SSE_READ_TIMEOUT_SEC', default=3600.0, cast=float)

# Максимальное число подряд неудачных попыток аутентификации.
VA_MAX_AUTH_FAILURES = config('VA_MAX_AUTH_FAILURES', default=3, cast=int)

# Максимальное число подряд неудачных SSE-сессий (< 30 сек).
VA_MAX_SSE_FAILURES = config('VA_MAX_SSE_FAILURES', default=10, cast=int)

# Backoff-лесенка перед автоматическим перезапуском упавшего парсера
# (в секундах): 1-я попытка почти сразу, дальше по нарастающей, чтобы не
# долбить реально сломанный VA API повторными логинами. Индекс — это
# (parser_restart_attempt - 1); значений в списке меньше, чем возможных
# попыток — сверх длины списка используется последнее (потолок).
PARSER_RESTART_BACKOFF_SCHEDULE_SEC = [30, 60, 180, 360, 600, 1800]

# Порог "протухшего" heartbeat для check_parser_heartbeats (сек). Раньше был
# фиксирован на 5 минут — при штатном keep-alive раз в ~30 сек это слишком
# долго ждёт обнаружения зависшего/убитого процесса, особенно для парсер-
# воркера на пуле потоков (--pool=threads), где SIGTERM-обработчик не может
# сработать (см. agromash/services/parse_event_runner.py).
PARSER_HEARTBEAT_TIMEOUT_SEC = config('PARSER_HEARTBEAT_TIMEOUT_SEC', default=120, cast=int)

# -----------------
# Видео-клипы Alarm (архив VMS)
# -----------------
# Отступы вокруг start_time/end_time алярма при скачивании клипа — даёт
# контекст "что было до/после", а не только точку детекции.
VIDEO_CLIP_PRE_ROLL_SEC = config('VIDEO_CLIP_PRE_ROLL_SEC', default=4.0, cast=float)
VIDEO_CLIP_POST_ROLL_SEC = config('VIDEO_CLIP_POST_ROLL_SEC', default=4.0, cast=float)

# Лимит суммарного размера video_clip на диске. На сервере свободно немного
# места (см. деплой-заметки) — 20 ГБ оставляет запас под ОС/Postgres/логи.
VIDEO_CLIP_STORAGE_QUOTA_BYTES = config(
    'VIDEO_CLIP_STORAGE_QUOTA_BYTES', default=20 * 1024 ** 3, cast=int
)

# Периодические задачи (Celery Beat)
CELERY_BEAT_SCHEDULE = {
    "send_due_telegram_reports_every_minute": {
        "task": "agromash.send_due_telegram_reports",
        "schedule": 60.0,
    },
    "send_due_email_reports_every_minute": {
        "task": "agromash.send_due_email_reports",
        "schedule": 60.0,
    },
    # Мониторинг heartbeat парсеров (каждые 2 минуты)
    # Раз в 20 сек — дёшево (таблица из нескольких строк), зато позволяет
    # backoff-лесенке реально достигать своих коротких ступеней (30с/60с).
    "check_parser_heartbeats_every_20_sec": {
        "task": "agromash.check_parser_heartbeats",
        "schedule": 20.0,
    },
    # Автоматический перезапуск парсеров в статусе error (каждые 2 минуты)
    "auto_restart_error_parsers_every_20_sec": {
        "task": "agromash.auto_restart_error_parsers",
        "schedule": 20.0,
    },
    # Квота на видео-клипы не time-sensitive — раз в 5 минут достаточно.
    "enforce_video_clip_storage_quota_every_5_min": {
        "task": "agromash.enforce_video_clip_storage_quota",
        "schedule": 300.0,
    },
}

# -----------------
# Logging
# -----------------
# Важно для systemd/journalctl: выводим логи в stdout/stderr.
# Это позволит видеть сообщения (в т.ч. auth VA API клиента) в:
#   journalctl -u btkanalitics-web.service -n 100 --no-pager -o short-iso
LOG_LEVEL = config('LOG_LEVEL', default='INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'short': {
            'format': '%(asctime)s %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'short',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}
